baseURL = "https://rikoroku.com/"
languageCode = "ja-jp"
title = "rikoroku.com"
theme = "kiss"
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.social]
twitter = "rikoroku_ja"
github = "rikoroku"
email = "rikoroku.55@gmail.com"
instagram = "rikoroku_ja"
about = "resume"
rss = 'index.xml'

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","about","rss"]

[blackfriday]
hrefTargetBlank = false
