baseURL = "https://rikoroku.github.io/blogs/"
languageCode = "ja-jp"
title = "blogs"
theme = "kiss"
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.social]
github = "rikoroku"
instagram = "/photos/"
about = "resume"
rss = 'index.xml'

[params.social.config]
platforms = ["github","instagram","about","rss"]

[blackfriday]
hrefTargetBlank = false
