version: '3'

services:
  hugo:
    container_name: hugo
    build:
      context: .
    image: dceoy/hugo:latest
    ports:
      - 1313:1313
    volumes:
      - .:/blog
    working_dir: /blog/hugo
    entrypoint:
      - /opt/go/bin/hugo
    command:
      - server
      - --bind=0.0.0.0
      - --watch
